### ISSUE TITLE
Example Python usage results in import error

### ISSUE THREAD

**Issue by ReinderVosDeWael** [Ars-Linguistica/mlconjug3#442]
**Describe the bug**
The [example usage](https://mlconjug3.readthedocs.io/en/latest/usage.html#using-the-conjugator-class) shows an import of the conjugator module. This import errors with a `ModuleNotFoundError`.

**To Reproduce**
```python
>>> import mlconjug3
>>> mlconjug3.__version__
'3.10.3'
>>> from mlconjug3.conjugator import Conjugator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mlconjug3.conjugator'
```

**Expected behavior**
The import succeeds, or the documentation shows the correct import.

**Desktop (please complete the following information):**
 - OS: macOS, macbook pro M1

**Comment by SekouDiaoNlp** [comment]
Hi @ReinderVosDeWael ,

the correct imports are:
>>> import mlconjug3

>>> from mlconjug3 import Conjugator

I will update the documentation as soon as possible.

Thanks for letting le kniw.
